- .dockerignore
- .github/workflows/ci-dev-pr.yml
- .github/workflows/ci-dev.yml
- .github/workflows/lint.yml
- .github/workflows/production.yml
- .gitignore
- Dockerfile
- docker-compose.yml
- poetry.lock
- pyproject.toml
- src/main.py
Deploy DuckBot to AWS using Github Actions and Docker.
- Add ci-dev, ci-dev-pr and production workflows
- Add Dockerfile and docker-compose
N/A
N/A
> feat(ci): Add Dockerfile and workflows

- README.md
- src/main.py
Update readme and load environment variables properly  
- Load environment variables properly.
- Update README.md to include commands for adding Poetry to PATH.
N/A
N/A
> docs: Update readme and load environment variables properly  

- src/commands/skullboard.py
Unterminated string literal issue fixed
Unterminated string literal issue fixed
N/A
N/A
> fix: String literal issue fixed

- .github/workflows/production.yml
Add env variables to production workflow.
Add env variables to production workflow.
N/A
N/A
> fix: Add env variables to production workflow

- src/commands/skullboard.py
Use ephemeral messages for skullboard commands
Use ephemeral messages for skullboard commands to reduce spam messages.
N/A
N/A
> chore: Use ephemeral messages for skullboard commands

- src/main.py
Use ephemeral messages for pings / pongs. 
N/A
N/A
N/A
> chore: use ephemeral messages for pings / pongs

- src/commands/skullboard.py
- src/main.py
- src/models/database.py
- src/utils/time.py
Fixed bug where the calculated day wouldn't roll over on 00:00
Added timestamp to logger
> fix: Datetime rollover on 00:00

- src/commands/skullboard.py
Fix unterminated string literals error.
Fix unterminated string literals error.
N/A
N/A
> fix: Unterminated string literals formatted properly

- src/commands/gemini.py
Improve system instructions to decrease prompt injection.
- Remove unused imports.
- Increase harassment harm block threshold to block only high.
- Improve system instructions to decrease prompt injection.
N/A
N/A
> fix: Improve system instructions to decrease prompt injection

- src/main.py
Disable DMs.
Disable DMs by ignoring messages not sent in a server.
Fixes #65 
N/A
> fix: Disable DMs

- src/commands/gemini.py
Add try and exceptions for chat history.
- Add try and exceptions for chat history.
- Reduce how long chat history is kept.
Should hopefully fix issue #67.
N/A
> fix(chat): Add try and exceptions for chat history

- src/commands/help_menu.py
- src/main.py
Improving the help menu to have multiple pages utilizing buttons and a select menu to switch
- Changed the help menu system
- New class to manage the help menu
Fixes issue #42
> Feat: Improving the help menu

- src/commands/help_menu.py
- src/main.py
The select menu was indexing into an incorrect page number. Changed option list to include "Duckbot" for main page. 
- New option in select menu
- Fixed menu page list creation
N/A
N/A
> Fixing broken select menu

- src/commands/gemini.py
Remove broken delete files and change chat command title.
- Remove broken delete files.
- Change chat command title to "Ask DuckBot".
Should hopefully fix issue #67. 
N/A
> fix: Remove broken delete files and change chat command title

- src/commands/gemini.py
- src/main.py
Update bot references from Gemini to DuckBot.
Update bot references from Gemini to DuckBot.
N/A
N/A
> chore(chat): Update bot references from Gemini to DuckBot

- src/utils/spam_detection.py
Add another known spam message type.
Add another known spam message type.
N/A
N/A
> chore: Add another known spam message type

- src/utils/spam_detection.py
Update known spam messages (12-12-24).
Add two more known spam messages (12-12-24).
N/A
N/A
> chore(spam-detection): Update known spam messages (12-12-24)

- src/utils/spam_detection.py
Adjust threshold to improve spam detection.
Change threshold from 0.2 to 0.3 to better detect spam messages.
N/A
N/A
> chore(spam-detection): Adjust threshold

- src/utils/spam_detection.py
Update known spam messages (6-3-25)
Update known spam messages (6-3-25)
N/A
N/A
> chore(spam-detection): Update known spam messages (6-3-25)

- src/commands/faq.py
Date needed to be altered in order to not have a clash with a current event.
> chore: change date for fng event

- src/utils/spam_detection.py
Update known spam messages (6-6-25).
Update known spam messages (6-6-25).
N/A
N/A
> chore(spam-detection): Update known spam messages (6-6-25)

- src/commands/faq.py
Description
Dates needed to be altered in order to not have clashes with event schedule for Semester 2.
> chore: Change dates for fng events

- src/main.py
Update Gemini model to version 2.5 flash.
Update Gemini model to version 2.5 flash.
Fixes #97 
N/A
> chore: Update Gemini model to version 2.5 flash
